In [86]:
import pandas as pd
import os
import re

# Ruta del archivo CSV
csv_path = '../data/03_casos/df_52_cleaned.csv'

# Leer el CSV
df = pd.read_csv(csv_path)

# Obtener solo el nombre del archivo (sin ruta ni extensión)
file_name = os.path.splitext(os.path.basename(csv_path))[0]  # 'df_52_cleaned'

# Extraer el número entre los guiones bajos usando regex
match = re.search(r'_(\d+)_', file_name)
if match:
    sub_reg_nt = match.group(1)  # '52'
else:
    sub_reg_nt = None  # Por si no hay coincidencia

# Añadir la columna con el número extraído
df['sub_reg_nt'] = sub_reg_nt

In [87]:
df.head()

,ano,semana,ira_no_neumonia,neumonias_men5,neumonias_60mas,hospitalizados_men5,hospitalizados_60mas,defunciones_men5,defunciones_60mas,sub_reg_nt,...,defunciones_60mas_lag_3_semana,defunciones_60mas_lag_4_semana,defunciones_60mas_lag_5_semana,defunciones_60mas_lag_6_semana,mes,bimestre,trimestre,cuatrimestre,semestre,pandemia_covid
0,2000,1,2168,16,0,9,0,0,0,52,...,0.0,0.0,0.0,0.0,1,1,1,1,1,0
1,2000,2,1986,13,0,7,0,0,0,52,...,0.0,0.0,0.0,0.0,1,1,1,1,1,0
2,2000,3,1836,15,0,5,0,0,0,52,...,0.0,0.0,0.0,0.0,1,1,1,1,1,0
3,2000,4,1459,16,0,4,0,0,0,52,...,0.0,0.0,0.0,0.0,1,1,1,1,1,0
4,2000,5,1431,11,0,4,0,0,0,52,...,0.0,0.0,0.0,0.0,2,1,1,1,1,0

In [88]:
df = df[[
    'ano',
    'semana',
    'sub_reg_nt',
    'hospitalizados_men5',
]]

In [89]:
import pandas as pd
import requests
import json
import os
import re

# Crear lista de diccionarios para Power BI
payload = []
for _, row in df.iterrows():
    payload.append({
        "ano": str(row['ano']),
        "semana": str(row['semana']),
        "sub_reg_nt": str(row['sub_reg_nt']),
        "real_hospitalizados_men5": float(row['hospitalizados_men5']),
        "pred_hospitalizados_men5":  None   # sin valor por ahora
    })

# === 4️⃣ Enviar al endpoint de Power BI ===
endpoint = "https://api.powerbi.com/beta/37e0b05d-41da-4172-9c5f-b0fc5e15667e/datasets/05e1d5d6-02f7-412e-aa80-7e526fcc309c/rows?experience=power-bi&key=NRfvRQepSIDZiBChXLVBmqGgpwnotL8frml%2FRNbYGw5lwTgC9y1atrgi2jz91KHdi9Ha8bAPtCSeZrZ5GOkxdg%3D%3D"

headers = {
    "Content-Type": "application/json"
}

# Enviar los datos
response = requests.post(endpoint, data=json.dumps(payload), headers=headers)

# === 5️⃣ Mostrar resultado ===
if response.status_code == 200:
    print(f"✅ Datos enviados correctamente ({len(payload)} filas) al dataset de Power BI.")
else:
    print(f"❌ Error al enviar datos. Código: {response.status_code}")
    print("Detalle del error:", response.text)

✅ Datos enviados correctamente (1248 filas) al dataset de Power BI.

---

---

---

In [90]:
import pandas as pd
import os
import re

# Ruta del archivo CSV
csv_path = '../data/03_casos/df_52_cleaned_predicciones.csv'

# Leer el CSV
df = pd.read_csv(csv_path)

# Obtener solo el nombre del archivo (sin ruta ni extensión)
file_name = os.path.splitext(os.path.basename(csv_path))[0]  # 'df_52_cleaned'

# Extraer el número entre los guiones bajos usando regex
match = re.search(r'_(\d+)_', file_name)
if match:
    sub_reg_nt = match.group(1)  # '52'
else:
    sub_reg_nt = None  # Por si no hay coincidencia

# Añadir la columna con el número extraído
df['sub_reg_nt'] = sub_reg_nt

In [91]:
df = df[[
    'ano',
    'semana',
    'sub_reg_nt',
    'hospitalizados_men5_prediccion',
]]

In [92]:
df.head()

    ano  semana sub_reg_nt  hospitalizados_men5_prediccion
0  2024       1         52                        9.261293
1  2024       2         52                        7.607387
2  2024       3         52                        7.757575
3  2024       4         52                        7.130177
4  2024       5         52                        6.519816

In [93]:
import pandas as pd
import requests
import json

# Crear lista de diccionarios para Power BI
payload = []
for _, row in df.iterrows():
    payload.append({
        "ano": str(row['ano']),
        "semana": str(row['semana']),
        "sub_reg_nt": str(row['sub_reg_nt']),
        "real_hospitalizados_men5": None,  # ahora el real va nulo
        "pred_hospitalizados_men5": float(row['hospitalizados_men5_prediccion'])  # valor de la predicción
    })

# === Enviar al endpoint de Power BI ===
endpoint = "https://api.powerbi.com/beta/37e0b05d-41da-4172-9c5f-b0fc5e15667e/datasets/05e1d5d6-02f7-412e-aa80-7e526fcc309c/rows?experience=power-bi&key=NRfvRQepSIDZiBChXLVBmqGgpwnotL8frml%2FRNbYGw5lwTgC9y1atrgi2jz91KHdi9Ha8bAPtCSeZrZ5GOkxdg%3D%3D"

headers = {
    "Content-Type": "application/json"
}

# Enviar los datos
response = requests.post(endpoint, data=json.dumps(payload), headers=headers)

# === Mostrar resultado ===
if response.status_code == 200:
    print(f"✅ Datos enviados correctamente ({len(payload)} filas) al dataset de Power BI.")
else:
    print(f"❌ Error al enviar datos. Código: {response.status_code}")
    print("Detalle del error:", response.text)

✅ Datos enviados correctamente (364 filas) al dataset de Power BI.